name: Build APK and Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Decode and save rclone.conf
        run: |
          echo "${{ secrets.RCLONE_CONF_BASE64  }}" > rclone.conf

      - name: Upload APK to Google Drive
        run: |
          rclone copy build/app/outputs/flutter-apk/app-release.apk drive:CookingBuddy --config=rclone.conf

      - name: Get Shareable Google Drive Link
        id: drive_link
        run: |
          LINK=$(rclone link drive:CookingBuddy/app-release.apk --config=rclone.conf)
          echo "download_url=$LINK" >> $GITHUB_OUTPUT

      - name: Send email with APK link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 📦 New Cooking Buddy APK Build Available
          to: vishal444m@gmail.com
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            ✅ A new Cooking Buddy APK has been built and uploaded to Google Drive!

            👉 Download it here:
            ${{ steps.drive_link.outputs.download_url }}

            🕓 Build Time: ${{ github.event.head_commit.timestamp }}
